# Two ways of calculating the sample variance

In [1]:
import numpy as np

In [4]:
u=np.array([1,2])/np.sqrt(5)
u

array([0.4472136 , 0.89442719])

In [24]:
x1=np.array([1,2])
x2=np.array([3,4])
x3=np.array([-1,0])
x=np.array([x1,x2,x3])
N=x.shape[0]
x

array([[ 1,  2],
       [ 3,  4],
       [-1,  0]])

# Type 1 - The straight way

In [13]:
def dot(x):
    return np.dot(x,u)
result=np.apply_along_axis(dot, axis=1, arr=x)
result

array([ 2.23606798,  4.91934955, -0.4472136 ])

In [20]:
shifted=result-result.mean()
shifted

array([ 4.44089210e-16,  2.68328157e+00, -2.68328157e+00])

In [25]:
np.power(shifted,2).sum()/N

4.8

# Type 2 - the projection way

In [82]:
u.T@x.T@(np.identity(N)-np.ones((N,N))/N)@x@u/N

4.8