# Three ways of calculating sample covariance

In [229]:
import numpy as np

In [263]:
# col vectors
x1=np.array([8,4,7])
x2=np.array([2,8,1])
x3=np.array([3,1,1])
x4=np.array([9,7,4])
x=np.array([x1,x2,x3,x4]).T
N=x.shape[1]
x

array([[8, 2, 3, 9],
       [4, 8, 1, 7],
       [7, 1, 1, 4]])

# Type 1 - numpy library

In [264]:
np.cov(x, bias=True)

array([[9.25  , 1.    , 6.375 ],
       [1.    , 7.5   , 0.    ],
       [6.375 , 0.    , 6.1875]])

# Type 2 - for loop (sum)

In [265]:
# sample mean (accross cols)
x_bar=x.mean(axis=1)
x_bar

array([5.5 , 5.  , 3.25])

In [276]:
def cov_iter( x ):
    print(x)
    m=x-x_bar
    return np.outer(m,m) # Outer vector product

result=np.apply_along_axis(cov_iter, axis=0, arr=x)
result

[8 4 7]
[2 8 1]
[3 1 1]
[9 7 4]


array([[[  6.25  ,  12.25  ,   6.25  ,  12.25  ],
        [ -2.5   , -10.5   ,  10.    ,   7.    ],
        [  9.375 ,   7.875 ,   5.625 ,   2.625 ]],

       [[ -2.5   , -10.5   ,  10.    ,   7.    ],
        [  1.    ,   9.    ,  16.    ,   4.    ],
        [ -3.75  ,  -6.75  ,   9.    ,   1.5   ]],

       [[  9.375 ,   7.875 ,   5.625 ,   2.625 ],
        [ -3.75  ,  -6.75  ,   9.    ,   1.5   ],
        [ 14.0625,   5.0625,   5.0625,   0.5625]]])

In [269]:
result.sum(axis=2)/N

array([[9.25  , 1.    , 6.375 ],
       [1.    , 7.5   , 0.    ],
       [6.375 , 0.    , 6.1875]])

# Type 3 - Matrix operation

In [271]:
ones=np.ones(N)
X=x.T
X

array([[8, 4, 7],
       [2, 8, 1],
       [3, 1, 1],
       [9, 7, 4]])

In [272]:
X.T@X/N-X.T@np.outer(ones,ones)@X/N/N

array([[9.25  , 1.    , 6.375 ],
       [1.    , 7.5   , 0.    ],
       [6.375 , 0.    , 6.1875]])